Worked on #15 issue
keploy/website-archive pull request #17
Opened 2023-01-09 18:18 UTC by ItsRoy69

2023-01-10 08:29 UTC, nehagup requested changes

2023-01-10 08:29 UTC, nehagup commented on CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
It seems you have picked this template from "Contributor Covenant. Can you please make the relevant changes for Keploy?

2023-01-10 08:29 UTC, nehagup commented on README.md
> +    <img src=".github/slack.svg" /></a>
I checked the "rich text" display/view. It is still not showing the badges. 🤔

2023-01-10 15:14 UTC, ItsRoy69 commented on CODE_OF_CONDUCT.md
> +# Contributor Covenant Code of Conduct
Made necessary changes and pushed in https://github.com/ItsRoy69/website/blob/main/CODE_OF_CONDUCT.md

If possible checkout and I will make another pull request

2023-01-10 15:16 UTC, ItsRoy69 commented on README.md
> +    <img src=".github/slack.svg" /></a>
![image](https://user-images.githubusercontent.com/78967360/211589281-0ad738f9-3636-4009-a1ac-7477236f8407.png)

This is showing in my current repo https://github.com/ItsRoy69/website 😅..

2023-01-18 17:05 UTC, nehagup commented
@ItsRoy69 can you please sign the DCO?

2023-01-19 14:16 UTC, ItsRoy69 commented
@nehagup made the necessary changes can you look into it please ?

2023-01-19 15:58 UTC, nehagup requested changes
The email we publicly refer is hello [at] keploy.io. Rest looks good! 👏

2023-02-08 10:52 UTC, nehagup approved these changes
LGTM!

2023-02-08 10:53 UTC, merged