Updated Contributing.md, readme.md, codeofconduct.md
keploy/website-archive pull request #23
Opened 2023-02-14 16:46 UTC by ItsRoy69

2023-02-14 17:28 UTC, nehagup requested changes
@ItsRoy69 can you please add installation and local dev guide for this project?

2023-02-15 15:34 UTC, ItsRoy69 commented
Updated the guides @nehagup can yopu check please ?

2023-02-24 05:35 UTC, slayerjain submitted a review, later dismissed
@ItsRoy69 can you please add a description on why have you removed a few supported framework images? Also what are the index.html changes regarding to?

2023-02-28 15:50 UTC, nehagup approved these changes

2023-02-28 15:51 UTC, merged